### ISSUE TITLE
Missing requirement.txt when installing via pip?

### ISSUE THREAD

**Issue by Guilouf** [Aluriak/pydelaunator#1]
This is for Pythonh 3.6 on Kubuntu:

guigui@gui-ZBook:~$ python3.6 -m pip install pydelaunator
Collecting pydelaunator
  Using cached pydelaunator-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pip/download.py", line 413, in get_file_content
        with open(url, 'rb') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-5rc2ki0i/pydelaunator/requirements.txt'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5rc2ki0i/pydelaunator/setup.py", line 14, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-build-5rc2ki0i/pydelaunator/setup.py", line 14, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/usr/lib/python3/dist-packages/pip/req/req_file.py", line 84, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "/usr/lib/python3/dist-packages/pip/download.py", line 417, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: '/tmp/pip-build-5rc2ki0i/pydelaunator/requirements.txt'
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
        import apport.fileutils
      File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
        from apport.packaging_impl import impl as packaging
      File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
        import apt
      File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
        import apt_pkg
    ModuleNotFoundError: No module named 'apt_pkg'
    
    Original exception was:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pip/download.py", line 413, in get_file_content
        with open(url, 'rb') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-5rc2ki0i/pydelaunator/requirements.txt'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5rc2ki0i/pydelaunator/setup.py", line 14, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-build-5rc2ki0i/pydelaunator/setup.py", line 14, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/usr/lib/python3/dist-packages/pip/req/req_file.py", line 84, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "/usr/lib/python3/dist-packages/pip/download.py", line 417, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: '/tmp/pip-build-5rc2ki0i/pydelaunator/requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5rc2ki0i/pydelaunator/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by Aluriak** [comment]
It is now fixed, and uploaded to pypi.
