### ISSUE TITLE
Error with pydelaunator.log

### ISSUE THREAD

**Issue by Guilouf** [Aluriak/pydelaunator#5]
The problem is when the log folder does not already exist, i have to create it.
```
guigui@gui-ZBook:~$ python3.6 -m pydelaunator
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/guigui/.local/lib/python3.6/site-packages/pydelaunator/__init__.py", line 2, in <module>
    from pydelaunator.edge import Edge
  File "/home/guigui/.local/lib/python3.6/site-packages/pydelaunator/edge.py", line 1, in <module>
    from pydelaunator import geometry, Vertex
  File "/home/guigui/.local/lib/python3.6/site-packages/pydelaunator/geometry.py", line 13, in <module>
    from pydelaunator.commons import sliding
  File "/home/guigui/.local/lib/python3.6/site-packages/pydelaunator/commons.py", line 5, in <module>
    from pydelaunator.setup_logging import logger
  File "/home/guigui/.local/lib/python3.6/site-packages/pydelaunator/setup_logging.py", line 24, in <module>
    handler = logging.FileHandler('logs/{}.logs'.format(PACKAGE_NAME))
  File "/usr/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/guigui/logs/pydelaunator.logs'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/guigui/.local/lib/python3.6/site-packages/pydelaunator/__init__.py", line 2, in <module>
    from pydelaunator.edge import Edge
  File "/home/guigui/.local/lib/python3.6/site-packages/pydelaunator/edge.py", line 1, in <module>
    from pydelaunator import geometry, Vertex
  File "/home/guigui/.local/lib/python3.6/site-packages/pydelaunator/geometry.py", line 13, in <module>
    from pydelaunator.commons import sliding
  File "/home/guigui/.local/lib/python3.6/site-packages/pydelaunator/commons.py", line 5, in <module>
    from pydelaunator.setup_logging import logger
  File "/home/guigui/.local/lib/python3.6/site-packages/pydelaunator/setup_logging.py", line 24, in <module>
    handler = logging.FileHandler('logs/{}.logs'.format(PACKAGE_NAME))
  File "/usr/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/guigui/logs/pydelaunator.logs'

```

**Comment by Aluriak** [comment]
Yes, the log folder is searched in the working directory. I should already have fixed that.

**Comment by Aluriak** [comment]
It's fixed now ! If there is no `logs/` in working directory, no logs will be written.
